version: 1
metadata:
  name: xrv-fspec-grpc
  kind: profile
profile:
  match:
    sysobjectid:
      - 1.3.6.1.4.1.9.1.2264
    features:
      - gnmi
  reports:
    - xrv-fspec-grpc
  include:
    - device_name_ip
  sources:
    - xrv-fspec-grpc